### ISSUE TITLE
App crashes when  trying to create notification with icon

### ISSUE THREAD

**Issue by magbe08** [Swiftnesses/com.lametric#10]
Hi!

When trying to create notification with icon, the app com.lametric crashes. Regular notifications work fine, sound also. Repeatable using Homey desktop app. When trying to do this on new iOS-app I get "Something went wrong", but the app does not crash.

Tried restarts, reinstalls.

System is at 1.5.11, app at 1.0.4. English language, swedish timezone.

Log may be available as 713d7a5f-f0ba-4399-b236-de99ae8f77be

![image](https://user-images.githubusercontent.com/39587847/40589863-8698241c-61f5-11e8-8272-26a2e897acea.png)

**Comment by RuudV376** [comment]
I have the same problem. Choosing an icon does not work, give the small red triangle in the flow action. Indeed, sometimes this crashes the app. Homey 1.5.11, English, Dutch timezone.
Homey restarted, PTP, no success yet.

**Comment by jameswoudenberg** [comment]
good idea, my test results are on the Athom forum. Problem also exist in your fork, crash happens seconds after opening the icon menu.

**Comment by magbe08** [comment]
Saw that @irritanterik has updated https://github.com/irritanterik/com.theswifties.lametric to v1.0.5. I guess this version does not fix the issues above as comment only states 

> v 1.0.5 added dutch labels and logging

Can anyone confirm this is the case?

**Comment by Swiftnesses** [comment]
I've implemented a fix on my fork, it's not the amount of icons per se, it's more the fact that La Metric now paginate icon results. Soon I'll make the caching multithreading, but for now it works...
