### ISSUE TITLE
widgets unavailable

### ISSUE THREAD

**Issue by ferdw** [Swiftnesses/com.lametric#6]
Trying to use the widget card, but there is no widget available. Lametric software version 2.0.5, Homey Firmware Versie: 1.5.4.
![image](https://user-images.githubusercontent.com/10448491/34649834-f85dffa2-f3b6-11e7-94a2-964dd02efe85.png)

**Comment by irritanterik** [comment]
fixed with https://github.com/Swiftnesses/com.lametric/pull/7

**Comment by RuudV376** [comment]
I have the same issue. Widgets do not show up in the drop down list. I (only) have the default LaMetric apps installed

**Comment by irritanterik** [comment]
fix is still not released
